const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  primary: '#fff',
  secondary: '#EE596C',
  topBar: '#EE596C',
  blue: '#4a90e2',
  blueLight: '#4a90e280',
  red: '#d33c14',
  redLight: '#d33c1480',
  green: '#70ad4d',
  greenLight: '#70ad4d80',
  lightGrey: '#EFF0F1',
  text: '#4a4a4a',
  lightText: '#323a44',
  lighterText: '#9b9b9b',
};
